<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="style.css" type="text/css" />
</head>
<body>
    <header>
        <a href="index.php">Connexion</a>
        <a href="signup.php">Inscription</a>

    </header>
   
    
    <main>
        
        <?php include "$template.phtml" ?>
        
    </main>
    
    
</body>
</html>