<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="style/style.css" type="text/css" />
</head>
<body>
    <header>
        <a href="index.php">Accueil</a>
        <a href="login.php">Connexion</a>
        <a href="register.php">Inscription</a>
        <a href="userAccount.php">Compte</a>
    </header>
    <main>
        
        <?php include "$template.phtml" ?>
        
    </main>
    
    
</body>
<footer>
    Tous les personnages mentionnés appartiennent à leurs franchises respectives. Je ne possède aucun droit sur eux.
</footer>
</html>