<body>
    <main class="contact-form">
                    <div class="info">
    <form class = "contact-form" action="login.php" method="POST">
        <h2>Connexion</h2>
                <label for="email">Email</label>
                <input type="text" id="email" name="email" placeholder="Entrez votre email" required>
                <label for="password">Mot de passe</label>
                <input type="password" id="password" name="password" placeholder="Entrez votre mot de passe" required>
        <button class="submit" type="submit">Se connecter</button>
    </form>
    </div>
    <?php if (isset($error)) { echo "<p>$error</p>"; } ?>
    </main>
</body>
